# Generated by Django 5.2.6 on 2025-10-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Book_No", models.CharField(max_length=100)),
                ("Book_Name", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=255)),
                ("Phone_No", models.CharField(max_length=15)),
            ],
        ),
    ]
